name: Release Build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      matrix:
        platform:
          - { os: linux, arch: amd64, ext: "" }
          - { os: linux, arch: arm64, ext: "" }
          - { os: darwin, arch: amd64, ext: "" }
          - { os: darwin, arch: arm64, ext: "" }
          - { os: windows, arch: amd64, ext: ".exe" }
          - { os: windows, arch: arm64, ext: ".exe" }

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # for git describe

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Initialize dependencies
        run: go mod tidy

      - name: Build binary
        env:
          GOOS: ${{ matrix.platform.os }}
          GOARCH: ${{ matrix.platform.arch }}
          EXT: ${{ matrix.platform.ext }}
          VERSION: $(git describe --tags 2>/dev/null || echo v0.0.0)
          COMMIT: $(git rev-parse --short HEAD 2>/dev/null || echo 0000000)
        run: |
          CGO_ENABLED=0 go build -ldflags "-X 'main.version=$VERSION' -X 'main.commit=$COMMIT'" \
          -o "dist/catall_${GOOS}_${GOARCH}${EXT}" main.go

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/catall_*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
